name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/rust.yml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: |
        cargo +nightly fmt -- --check
        cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
